In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.1.0+cu121


In [ ]:
scalar = torch.tensor(7)
scalar


tensor(7)

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape


torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.shape


torch.Size([2, 2])

In [ ]:
MATRIX.ndim

2

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR


tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][1]

tensor([4, 5, 6])

In [ ]:
random_tensor = torch.rand(3,5)
random_tensor


tensor([[0.9600, 0.6641, 0.3836, 0.6028, 0.1651],
        [0.4895, 0.5115, 0.8976, 0.8883, 0.4791],
        [0.2373, 0.5902, 0.7026, 0.4209, 0.7638]])

In [ ]:
random_image_tensor = torch.rand(size = (224,224,3))
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(3,3)

ones = torch.ones(3,3)
zeros, ones

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]))

In [ ]:
oneToTen = torch.arange(1,11,1)
oneToTen

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
tenZeros = torch.zeros_like(oneToTen)
tenZeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float32Tensor = torch.tensor([3.,6.,9.],
                             dtype = None,
                             device = None,
                             requires_grad=False)
float32Tensor.dtype


torch.float32

In [ ]:
float16Tensor = float32Tensor.type(torch.float16)
float16Tensor.dtype

torch.float16

In [ ]:
floatTensor = float16Tensor * float32Tensor
floatTensor.dtype

torch.float32

In [ ]:
x = torch.arange(1, 10)
x, x.shape



(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z = x.view(1,9)
z, z.shape


(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [ ]:
z[:, 0] = 5
x, z


(tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]), tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]))

In [ ]:
x_stacked = torch.stack([x,x,x], dim = 1)
x_stacked


tensor([[5, 5, 5],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8],
        [9, 9, 9]])

In [ ]:
x_squeezed = torch.squeeze(z)
x_squeezed

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x_unsqueezed = torch.unsqueeze(x_squeezed, dim = 1)
x_unsqueezed

tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [ ]:
x = torch.rand([224,224,3])
x_permuted = x.permute(2,0,1)
x.shape, x_permuted.shape


(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x[0,0,0] = 3000
x_permuted[0,0,0]

tensor(3000.)

In [ ]:
random_tensor = torch.rand(7,7)
random_vector = torch. rand(1,7)
mul_tensor = torch.matmul(random_tensor, random_vector.permute(1,0))
random_tensor, random_vector, mul_tensor


(tensor([[0.6817, 0.9253, 0.9999, 0.8650, 0.3413, 0.1118, 0.2656],
         [0.9431, 0.1893, 0.8246, 0.8360, 0.9171, 0.4455, 0.7260],
         [0.8881, 0.8825, 0.3878, 0.6354, 0.9919, 0.9215, 0.0698],
         [0.6979, 0.4239, 0.5966, 0.6697, 0.4104, 0.5529, 0.5785],
         [0.9675, 0.7957, 0.2889, 0.8491, 0.2615, 0.9145, 0.8998],
         [0.3310, 0.5925, 0.3159, 0.8915, 0.9134, 0.5125, 0.0478],
         [0.6569, 0.9801, 0.2675, 0.7688, 0.9701, 0.2617, 0.3395]]),
 tensor([[0.4163, 0.3999, 0.9816, 0.4632, 0.7398, 0.1126, 0.9228]]),
 tensor([[2.5462],
         [3.0635],
         [2.2997],
         [2.2556],
         [2.5247],
         [1.8753],
         [2.3445]]))

In [ ]:
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(7,7)

random_vector= torch.rand(1,7)
mul_tensor = torch.matmul(random_tensor, random_vector.permute(1,0))
random_tensor, random_vector, mul_tensor

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]))

In [ ]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
X = torch.rand(size=(7, 7))
Y = torch.rand(size=(1, 7))

# Matrix multiply tensors
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [ ]:
torch.cuda.manual_seed(1234)

In [ ]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)


cuda


In [ ]:
torch.manual_seed(1234)
X = torch.rand(2,3).to(device)

Y = torch.rand(2,3).to(device)
Z = torch.matmul(X, Y.T)
X, Y, Z


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'),
 tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'))

In [ ]:
torch.max(Z), torch.min(Z), torch.argmax(Z), torch.argmin(Z)

(tensor(0.5617, device='cuda:0'),
 tensor(0.3647, device='cuda:0'),
 tensor(3, device='cuda:0'),
 tensor(0, device='cuda:0'))

In [ ]:
torch.manual_seed(7)
X = torch.rand(size=(1,1,1,10))
Y = X.squeeze()
X, Y, X.shape, Y.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([1, 1, 1, 10]),
 torch.Size([10]))